Проектная работа - ревью
mr-algrin/blog-customizer pull request #1
Opened 2024-06-09 18:49 UTC by mr-algrin

Проектная работа по спринту "Основы React" выполнена.

2024-06-09 20:24 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Сборка и запуск проекта выполняются без ошибок;
- Внешний вид и расположение элементов страницы соответствует макету;
- После нажатия на “применить” стили применяются к статье;
- При повторном открытии сайдбара в нем сохраняются выбранные настройки;

### **Но есть несколько замечаний, которые нужно исправить:**

- Отметил небольшие замечания в коде.

### **Замечания можно лучше, необязательны к исправлению.**

2024-06-09 20:24 UTC, ArslanMustafin commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const onApply = useCallback(
**Можно лучше:**

здесь и далее.

Обычно одно использование useCallback ничего не решает, нужно более комплексный подход с применением и других хуков мемоизации. Тема оптимизации производительности рассмотрена в 12 спринте и лучше дождаться его, что бы лучше разобраться как применять её.

2024-06-09 20:24 UTC, ArslanMustafin commented on src/components/article-params-form/ArticleParamsForm.tsx
> +	const onClick = () => setIsOpen((prev) => !prev);
**Надо исправить:**

По заданию требуется реализовать закрытие по клику вне сайдбара, оно не реализовано. 
Вешать обработчик нужно при открытии сайдбара и удалять при закрытии. Для реализации этого в массиве зависимостей должен быть указан флаг управления отображением оверлея и в useEffect добавлена проверка, что оверлей открыт, и только в этом случае навешивать обработчики
Закрытие по ESC опционально для реализации.

```ts
// пример хука для закрытия внеобласти и по нажатию на esc

import { useEffect } from 'react';

type TUseClose = {
  isOpen: boolean,
  onClose: () => void,
  rootRef: React.RefObject<HTMLElement>,
};

export function useClose({ isOpen, onClose, rootRef }: TUseClose) {
  useEffect(() => {
    if (!isOpen) return; // останавливаем действие эффекта, если закрыто

    function handleClickOutside(event: MouseEvent) {
      const { target } = event;
      const isOutsideClick =
        target instanceof Node && // проверяем, что это `DOM`-элемент
        rootRef.current &&
        !rootRef.current.contains(target); // проверяем, что кликнули на элемент, который находится не внутри нашего блока
      if (isOutsideClick) {
        onClose();
      }
    }

    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };

    document.addEventListener('keydown', handleEscape);
    document.addEventListener('mousedown', handleClickOutside);

    //  обязательно удаляем обработчики в `clean-up`- функции
    return () => {
      document.removeEventListener('keydown', handleEscape);
      document.removeEventListener('mousedown', handleClickOutside);
    };
    // обязательно следим за `isOpen`, чтобы срабатывало только при открытии, а не при любой перерисовке компонента
  }, [isOpen, onClose, rootRef]);
}
```

Пример того, как это использовать:

```ts
// создаем `ref` для нашей формы и указываем его на внешнем блоке с формой
const formRef = useRef<HTMLElement>(null);

useClose({
  isOpen,
  onClose: () => setIsOpen(false),
  rootRef: formRef,
});
```

2024-06-09 23:08 UTC, mr-algrin commented
Исправлено

2024-06-10 08:07 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец! Работа принята, удачи в дальнейшем обучении!**

2024-06-10 08:07 UTC, ArslanMustafin commented on src/hooks/useOutsideClick.ts
> +export const useOutsideClick = <T extends HTMLElement>({
**Можно лучше:**

неиспользованный код лучше удалить)

2024-06-10 08:14 UTC, merged